### PR TITLE
GithubAuth.js2

### PR DESCRIPTION
**Pull request by IzziCooki**

### CODE REVIEW

**Comment by eternalmoon1234** [comment]
why does it look white

**Comment by IzziCooki** [comment]
No Idea I can just re submit it I guess

**Comment by eternalmoon1234** [comment]
K try that

**Comment by eternalmoon1234** [comment]
instead of creating a new server, instead just add it as a new route, so it would be

`const { Router } = require('express')

const route = Router()

route.get('stuff')

module.exports = route
`

**Comment by eternalmoon1234** [comment]
ok now re add the file

**Pull request closed without merging**
